baseurl = "https://sithum.online/blog/"
title = "Sithum's Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Hi 👋, I'm Sithum"
    description = "I post my Golang experience here"
    github = "https://github.com/sithumonline"
    twitter = "https://twitter.com/sithumonline"
    linkedin = "https://www.linkedin.com/in/sithumonline"
    stackoverflow = "https://stackoverflow.com/users/12165840/xeon"
    facebook = "https://www.facebook.com/sithumonline"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"